import { ModeToggle } from "@/components/ModeToggle";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Mailbox } from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";
import "../globals.css";

export const metadata: Metadata = {
  title: "Email Classifier",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-fit">
      <div className="flex items-center justify-between p-4 w-screen">
        <Link href="/" className="flex items-center justify-center">
          <div className="bg-gray-100 rounded-md">
            <Mailbox color="black" className="m-2" />
          </div>
          <h1 className="text-xl font-bold pl-4">Email Classifier</h1>
        </Link>
        <div className="flex items-center justify-center h-[36px]">
          <Link href="/classify">
            <Button variant="link" size="default" className="ml-2 mr-2">
              Classify{" "}
            </Button>
          </Link>
          <Separator orientation="vertical" />
          <Link href="/configure">
            <Button variant="link" size="default" className="ml-2 mr-2">
              Configure{" "}
            </Button>
          </Link>
          <Separator orientation="vertical" />
          <Link href="/analytics">
            <Button variant="link" size="default" className="ml-2 mr-2">
              Analytics{" "}
            </Button>
          </Link>
          <Separator orientation="vertical" />
          <ModeToggle />
        </div>
      </div>
      <Separator />
      <div>{children}</div>
    </div>
  );
}
