import { ModeToggle } from "@/components/ModeToggle";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Toaster } from "@/components/ui/sonner";
import { Keyboard } from "lucide-react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "2i1k",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main>
            {/* <div className="grid grid-rows-[3_1fr]"> */}
              <div className="h-fit">
                <div className="flex items-center justify-between p-4 w-screen">
                  <Link href="/" className="flex items-center justify-center">
                    <div className="bg-gray-100 rounded-md">
                      <Keyboard color="black" className="m-2" />
                    </div>
                    <h1 className="text-xl font-bold pl-4">Ctrl-Alt-Defeat</h1>
                  </Link>
                  <div className="flex items-center justify-center">
                  <Link href="/configure">
                  <Button variant="ghost" size="default" className="mr-4">
                    Configure{" "}
                  </Button>
                </Link>
                <Separator orientation="vertical" />
                    <ModeToggle />
                    
                  </div>
                </div>
                <Separator />
              </div>
              <div>{children}</div>
            {/* </div> */}
          </main>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
