import type { Metadata } from "next";
import "../globals.css";
import DockLayoutComponent from "./dockLayout";

export const metadata: Metadata = {
  title: "Email Classifier",
  description: "Generated by create next app",
};

export default function DockLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <DockLayoutComponent>{children}</DockLayoutComponent>;
}
